### ISSUE TITLE
Sample Prompts not importing

### ISSUE THREAD

**Issue by JuleKnowHow** [stuartridout/promptbuddy#1]
I'm having trouble importing the sample prompts. 

I am importing them as described in your Youtube-Video, and the Power Automate Flow is also completed successfully, but my tables are still all empty and the prompts don't show up in the "Prompt Buddy Admin" (which has "Manage Campaigns" as a title for me and the button that says "Add category" in the video says "Add campaign" for me - see attached image). 

<img width="743" alt="PromptBuddyAdmin" src="https://github.com/stuartridout/promptbuddy/assets/164504962/ad92d513-a0c3-4164-b3e1-2ea7a4f0393d">

**Comment by stuartridout** [comment]
That’s odd.  Do you have the Employee Ideas app installed in this environment?  StuartOn 22 Mar 2024, at 12:20, JuleKnowHow ***@***.***> wrote:﻿[stuartridout/promptbuddy] Sample Prompts not importing (Issue #1)I'm having trouble importing the sample prompts.I am importing them as described in your Youtube-Video, and the Power Automate Flow is also completed successfully, but my tables are still all empty and the prompts don't show up in the "Prompt Buddy Admin" (which has "Manage Campaigns" as a title for me and the button that says "Add category" in the video says "Add campaign" for me - see attached image).PromptBuddyAdmin.png (view on web)—Reply to this email directly, view it on GitHub or unsubscribe.You are receiving this email because you are subscribed to this thread.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JuleKnowHow** [comment]
No, in the environment there is only the Prompt Buddy installed right now.

**Comment by JuleKnowHow** [comment]
I have just checked the Flow again and I found that there actually is an error, despite the Flow being successfully called: 

Under the "Apply to each" section an error occurs in the "Parse Campaign JSON" element: 
_InvalidTemplate. Unable to process template language expressions in action 'Parse_Campaign_JSON' inputs at line '0' and column '0': 'Required property 'content' expects a value but got null. Path ''.'._

**Comment by stuartridout** [comment]
That's odd.  I've tried to repro but it works fine every time for us.  I would suggest deleting the flow and then downloading the latest release to see if it imports.

**Comment by JuleKnowHow** [comment]
I managed to get it to work. I had to manually create the categories for the sample prompts to be imported into. I assumed that they would also be created with the import, but they weren't.

**Comment by Erithano** [comment]
[like]  Erik Olsson reacted to your message:
________________________________

**Comment by Erithano** [comment]
Thanks @JuleKnowHow! The latest release has worked fine in this regard in multiple tests across various environments.
We're happy you resolved your issue with creativity and a bag of patience! 🙂

**Comment by halukpn** [comment]
I have a similar issue, everything seemed to import OK but I have no categories or anything.
![2024-04-30 09_31_10-Teams and Channels _ General _ UK Power Networks _ Hal Sclater@ukpowernetworks c](https://github.com/stuartridout/promptbuddy/assets/157490603/e0c1eec2-bb91-4702-bec9-6f23f1fdd61b)
