### ISSUE TITLE
Delete or Edit a Prompt

### ISSUE THREAD

**Issue by gsheeley** [stuartridout/promptbuddy#18]
How do you delete a Prompt.
or preferable Edit a prompt?

**Comment by Erithano** [comment]
@gsheeley Currently you delete a prompt from Prompt Buddy Manager. Only managers (Team owners) can delete a prompt.

Good news: Edit prompt & ability for regular users to delete and edit their own prompts will be shipping soooooooon 😉
We're currently in the last stage of testing these features.

**Comment by stuartridout** [comment]
Administrators can delete a prompt from Prompt Buddy Manager.   We’re just testing the latest release of Prompt Buddy which allows users to delete or edit their own prompts. On 23 Apr 2024, at 18:26, gsheeley ***@***.***> wrote:﻿[stuartridout/promptbuddy] Delete or Edit a Prompt (Issue #18)How do you delete a Prompt.or preferable Edit a prompt?—Reply to this email directly, view it on GitHub or unsubscribe.You are receiving this email because you are subscribed to this thread.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by stuartridout** [comment]
@gsheeley This has now been released!
