### ISSUE TITLE
Error when publishing the app on a channel

### ISSUE THREAD

**Issue by 5905** [stuartridout/promptbuddy#24]
We get a "request failed with status code 400" when publishing the app on a channel. 
We are owners for the team where we would like to publish this app

**Comment by cpsavage-henson** [comment]
I am having the same issue. I have tried pushing it to a couple of different teams, but no luck. I also deleted the app and re-installed with the same issue. Any ideas on how to resolve?

**Comment by stuartridout** [comment]
Are you publishing the app via the Power App app?  
Have your tenant admins blocked anything?
Are you following the video tutorial?

**Comment by cpsavage-henson** [comment]
I am using the instructions in the video verbatim. I am my tenant admin and I do not believe anything is blocked.

**Comment by Erithano** [comment]
Hope this issue has been resolved for you @cpsavage-henson & @5905.

Please update to the latest version of Prompt Buddy. Feel free to reopen this issue if still facing it after this message. 

First time installs, if you've never used Power Apps in your tenant before can cause a delay with your ability to add Prompt Buddy to a channel. This is due to first time run and setup of the Dataverse environment. Not related to Prompt Buddy 😇

**Comment by T00ma5z** [comment]
The issue is still happening. What was the resolution? How can I fix it?

**Comment by pezlin** [comment]
@T00ma5z Did you solve this?

**Comment by T00ma5z** [comment]
> [@T00ma5z](https://github.com/T00ma5z) Did you solve this?

yes, i did.

**Comment by pezlin** [comment]
@T00ma5z Any chance you can provide some details on how it was solved?

**Comment by T00ma5z** [comment]
> [@T00ma5z](https://github.com/T00ma5z) Any chance you can provide some details on how it was solved?

I was using power platform preview app instead of the regular app. Make sure you don't use preview app
