### ISSUE TITLE
Data Storage Location: Copilot Partner Community Question

### ISSUE THREAD

**Issue by karuanag** [stuartridout/promptbuddy#27]
Transferring this question from our Copilot Partner Community:

We're doing an adoption accelerator for a local government authority and they have asked if Prompt Buddy is "secure". Digging a bit deeper into their concerns, they are worried about where Prompt Buddy stores data. I'm not a Dataverse expert but Copilot says that Dataverse databases are stored within the tenant (which is good) but the data are maybe stored outside the tenants for backup purposes. It also says that the power app may or may not access and store date outside the tenant. Could we please get a definitive statement on how Prompt Buddy handles data to calm their nerves?
 
Thanks in advance

**Comment by stuartridout** [comment]
@karuanag Prompt Buddy doesn't connect to any data sources outside of the tenant.  It also doesn't send prompts or data to any external sources outside of the tenant.

In terms of the backup of the Dataverse environment I am not an expert but I couldn't find any sources that state that environments are backed up outside of the tenant.  

I did find "Unless otherwise stated in documentation, customer data remains in its original source (for example, Dataverse or SharePoint)."  More info at https://learn.microsoft.com/en-us/power-platform/admin/security/data-storage 

Also see - https://learn.microsoft.com/en-us/power-platform/admin/wp-security
