### ISSUE TITLE
Error: The solution file is invalid. 

### ISSUE THREAD

**Issue by treezie** [stuartridout/promptbuddy#39]
The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.

It appears that the .zip file doesn't contain an XML file. Am I doing something wrong?

**Comment by stuartridout** [comment]
HiYou need to grab the release rather than the repo.  On the right hand side of the GitHub repo it says Releases.   Download the latest release from there and you should be able to import it. StuartOn 12 Aug 2024, at 05:57, treezie ***@***.***> wrote:﻿[stuartridout/promptbuddy] Error: The solution file is invalid. (Issue #39)The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.It appears that the .zip file doesn't contain an XML file. Am I doing something wrong?—Reply to this email directly, view it on GitHub or unsubscribe.You are receiving this email because you are subscribed to this thread.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by stuartridout** [comment]
Hi

You need to grab the release rather than the repo.  On the right hand side of the GitHub repo it says Releases.   

Download the latest release from there and you should be able to import it.

**Comment by treezie** [comment]
Thank you for your reply, Stewart

I am very new to GitHub, greatly appreciated.

Kind regards

Luke
