### ISSUE TITLE
sub-categories

### ISSUE THREAD

**Issue by anthonyvigneron** [stuartridout/promptbuddy#53]
As we scale the usage and maturity of prompting, we really need either a 4th "category" (in addition to app/dept/persona), or a sub-category so we can assign prompts to specific workflows or group of activities.

**Comment by Yi-jiunTang** [comment]
We need this too.

**Comment by Erithano** [comment]
@anthonyvigneron & @Yi-jiunTang. 

**Good news!** 
While subcategories within a category aren't possible, I have the solution and a bonus tip for you 😇

### Solution: How to add a 4th "category type"
This is not in the UI admin app, but it's simple to add a category type. Anyone can do this.

Popular question:
_"I want to add/remove/rename our prompt category types!"_
![image](https://github.com/user-attachments/assets/11d3dc4d-1606-4355-a608-8497a579d248)

1. Open Power Apps app in Teams
2. Switch from Home to the Build tab
3. Click "**See all**" if necessary.
4. Open the table **Campaign Category**
![image](https://github.com/user-attachments/assets/7efd7e22-bf89-4970-a761-648ce20bc67f)

5. Click 🖋️Edit
6. Type your desired category type. DONE!
_(You can also rename Department to "Use Case" or whatever makes sense for you. 
Adding or deleting is also possible from here.)_

**Important:⚠️**

Do **NOT** change the word App. 
This category type must stay exactly as is, otherwise you won't be able to submit prompts.

💡Bonus tip: Use #hashtags in prompt descriptions to create unique categories users can find via the search bar.
