### ISSUE TITLE
No more Announcements

### ISSUE THREAD

**Issue by nyoung30** [stuartridout/promptbuddy#62]
Hello,

Thanks for the great work that has gone into Prompt Buddy, I really appreciate it!

I recently upgraded, set prompt approval to required and am no longer seeing new prompts being posted in the Announcements channel. 

I'm not certain if this is a Prompt Buddy or me issue. Any advice would be appreciated!

Thanks,
Norm

**Comment by Erithano** [comment]
Hi Norm! @nyoung30 

We appreciate your positive feedback! Your experience is by Design. 

When Approval is turned ON, notifications on new prompts are **not** triggered as they are yet to be approved and should not be announced before approved.

Currently, once approved, there is no notification being triggered.
